language: python
sudo: false
python:
    - "2.7"
addons:
    apt:
        packages:
        - python-wxgtk2.8
        - python-pygame
        - python-jinja2
        - python-yaml
virtualenv:
      system_site_packages: true
install:
    - pip install flake8 pylint nose
    - python setup.py install
script:
    - pylint wiggler/core wiggler/engine wiggler/ui || true
    - python setup.py flake8
    - nosetests -v
